language: node_js
node_js:
- 6.9.1
cache:
  directories:
  - ~/.nvm
  - node_modules
git:
  depth: 1
env:
  global:
  - RELEASE_BRANCH="master"
  - MAIN_BRANCHES="master develop"
  - secure: 2CPxFS5CkXwJpzqJ4VsKzkjjlFQ5vaqQSbnPA/bEdz5EOY65ypH4fvysI3CyW02Kvw3Gn5LoWMdDrnwOMWsidQwti5KgN5sf4SlvsYX+GJJmUAAkVFiRT6y3LPTeR4d6eRZH3kgsUJet3e6SMGp0gaq2SgRxzkAi3NKene8TxBlps/Y3ORWryME+6xG7AX8y4tWHDOhKohGc6Lo6xicoQ9a3SwXld+f1xMtJDPLHx3khXcsuRWf4jIV9DqrKM481zbqk/fahp6UIUyzUGpO1yPBxGu4238ZtWzj8wuQeyXgfJEd1sMzhRqxZ7NApLKY0YVXgY4sf2MvgyySBKe8JC4bxYfj1W3KXq9bfkGy/TxdZK/hyhQYFo9uBFkJ+zWFBMzkAETji04lZcxuKvkrdibE/SnPn4TkXkNCR5keuQVK1KSkSTHMELQh+KtLCrNEAEh2Y6160OrpHR9N5GhPYn7pX7bVbG84Omj/mBItA3jNpAViR0xIFyVivf6yZuarU+0rT8u8BooF/57wWmaTcCRPsuDh6YNhFAT05zaiQj7nJb6LGH7xACy87Q1Id+SIcuuc6tq98q/BKJkxU7Zgung2poCekZr+NZr+RYrKjaw+Eg1dhagqrIBHeMTn38EVHJFsW8Vn8ruz2/Kc2otQBTTPn80crpzlxXHDIRlCu1Vg=
before_script:
- chmod -R +x bin
- ./bin/version-increment.sh || { exit 1; }
- npm run build
script:
- npm run lint && npm test || { exit 1; }
after_success:
- ./bin/ci/push.sh
deploy:
  provider: npm
  email: alexeybondarenko@me.com
  skip_cleanup: true
  api_key:
    secure: iM39sfIqGNiIHx6XEeT/M4MrBk9gsMRcAtgknPpKClpOUUxJukdRylsCKco1SRriQZQR/kGRcJqopznxyz3zExDHHRti672eP8z5xTPJx73mPvA9X4+wWn/t/ZtAjDGm7B+KXfDkXywEMZXUNmeKCq9oDyOo2D8cAZGuBgkE1OEB/X2IiKLijQZ4LBpqX6uodcpyHO/TIaTyoQAtNebcenVyMnG3dRL/S7pYMz3hOVV2AhxH2c0ZBE62OcfYclI8gL+Qf5g3but6GZCqw4HAi3dCm4ezgEOeoaUTqcPshbHsA/HN3usmqwrCSdS+BoW+OWPsIzZ6jIoF58K+ZL2ClCqFD5gPC8eXTMTKl4FDWQM+bh5a0lJUiGdFaa4+mAE+n7RMApuZB7DBVZPNGSSzyyJWHm6NOZDIyg5AvzypDGUyeE+kj4MCm5xP22y9sanZND5nG4tPcXg8rF07GnC2M+vdFhwZnY7F12lbEu53cj7JavcOkKAXg1SoiMQISmt8xkxOcUtWxVv/Axt3Pta91uEQitGFTrWB1v9fvVAM1TBkd+UgH//0JVfoPTciLwf1aCEhQlxaCuGmyWHWAOpCxHos+dEZSpCq6Mehw5D6ec7diHnrJ4Qh6S3iiZdEUTbORmO10r8H1dX4We16tsvo8GJDmRhL8v7xbTHKS8LJh0M=
  on:
    branch: master
    repo: Nebo15/react-nebo15-validate
